#!/bin/bash

#######################################
# GET FROM CLI ARGUMENTS
#######################################
ID=goliatone/hello-rabbit
TAG=latest
TARGET_DIR=/tmp/$(cat /proc/sys/kernel/random/uuid)

for i in "$@"
do
case $i in 
    -i=*|--id=*)
      ID="${i#*=}"
      shift #past argument=value
    ;;
    -i*|--id*)
      ID="$2"
      shift 2
    ;;
    -t=*|--tag=*)
      TAG="${i#*=}"
      shift
    ;;
    -t*|--tag*)
      TAG="$2"
      shift
    ;;
esac
done

echo "ID $ID"
echo "TAG $TAG"

#######################################
echo "Cloning repo: $ID into $TARGET_DIR"

#git clone --recursive git@github.com:$ID.git $TARGET_DIR
git clone --recursive https://github.com/$ID.git $TARGET_DIR

if [ $? -ne 0 ]; then
    echo "Git clone failed... move on"
    exit 1
fi

echo "Moving into repo..."
cd $TARGET_DIR


#CONTAINERS=$(docker ps -q)

#if [ -n "$CONTAINERS" ]; then
#    echo "Stoping running containers $CONTAINERS"
#    ! docker stop $CONTAINERS
#else
#    echo "No containers to remove."
#fi

echo "docker build -t $ID..."
docker build --rm -t $ID .

echo "docker push $ID:$TAG..."
docker push $ID:$TAG

echo "Cleaning up trash..."
rm -r $TARGET_DIR
